baseurl = ""
relativeurls=true
title = "Programar en cloud"
languageCode = "es-ES"
disqusShortname = "programarcloud"
copyright = "Copyright (c) 2016-2017, Javi Moreno; Creative Commons sobre el contenido creado."
MetaDataFormat = "yaml"

[author]
    name = "Javi Moreno"

[taxonomies]
    tag = "tags"
    tema = "temas"
    curso = "cursos"
    nivel = "niveles"
